CREATE TABLE USERS (
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL PRIMARY KEY,
user_inactive BOOLEAN NOT NULL DEFAULT FALSE,
user_password VARCHAR(70) NOT NULL,
cellphone VARCHAR(10) NOT NULL,
image BLOB NOT NULL);


CREATE TABLE SELLER (
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL PRIMARY KEY,
user_inactive BOOLEAN NOT NULL DEFAULT FALSE,
user_password VARCHAR(70) NOT NULL,
cellphone VARCHAR(10) NOT NULL,
image BLOB DEFAULT("Image"));

CREATE TABLE PRODUCT (
title VARCHAR(50) NOT NULL,
imageurl mediumtext,
price VARCHAR(5) NOT NULL,
description_product VARCHAR(50) NOT NULL,
ingredients VARCHAR(200) NOT NULL,
ownerid VARCHAR(100) NOT NULL,
available BOOLEAN NOT NULL DEFAULT TRUE,
id VARCHAR(100) NOT NULL PRIMARY KEY,
vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
glutenfree BOOLEAN NOT NULL DEFAULT FALSE,
lactosefree BOOLEAN NOT NULL DEFAULT FALSE,
vegan BOOLEAN NOT NULL DEFAULT FALSE,
desayuno BOOLEAN NOT NULL DEFAULT FALSE,
comida BOOLEAN NOT NULL DEFAULT TRUE,
snack BOOLEAN NOT NULL DEFAULT FALSE,
lonche BOOLEAN NOT NULL DEFAULT FALSE,
sandiwch BOOLEAN NOT NULL DEFAULT FALSE,
taco BOOLEAN NOT NULL DEFAULT FALSE,
pan BOOLEAN NOT NULL DEFAULT FALSE,
dulce BOOLEAN NOT NULL DEFAULT FALSE,
estandar VARCHAR(50) NOT NULL DEFAULT "CHEAP"
);

CREATE TABLE BUY (
email VARCHAR(100) NOT NULL,
idbuy VARCHAR(100) NOT NULL PRIMARY KEY,
ownerid VARCHAR(100) NOT NULL,
isbuy BOOLEAN NOT NULL DEFAULT FALSE,
idproduct VARCHAR(100) NOT NULL,
fecha VARCHAR(20) NOT NULL
);